package domain

type Order struct {
	Tl_id2         string `json:"tl_id2"`
	Label_date     string `json:"label_date"`
	Brand          string `json:"brand"`
	Product        string `json:"product"`
	Template       string `json:"template"`
	Brand_logos    string `json:"brand_logos"`
	Atrb_logos     string `json:"atrb_logos"`
	Label_name     string `json:"label_name"`
	Plu_nmr        string `json:"plu_nmr"`
	Bar_code       string `json:"bar_code"`
	Price          string `json:"price"`
	Sale_price     string `json:"sale_price"`
	Sale_dates     string `json:"sale_dates"`
	Distb          string `json:"distb"`
	Distb_id       string `json:"distb_id"`
	Og_cert        string `json:"og_cert"`
	Ngmo_cert      string `json:"ngmo_cert"`
	Ngmo_exp       string `json:"ngmo_exp"`
	Ft_pct         string `json:"ft_pct"`
	Wg_logo        string `json:"wg_logo"`
	Roc_cert       string `json:"roc_cert"`
	Details        string `json:"details"`
	Supplier       string `json:"supplier"`
	Country        string `json:"country"`
	Ingredients    string `json:"ingredients"`
	Serv_size      string `json:"serv_size"`
	Serv_size_1    string `json:"serv_size_1"`
	Serv_size_2    string `json:"serv_size_2"`
	Calories       string `json:"calories"`
	Total_fat      string `json:"total_fat"`
	Dv_fat         string `json:"dv_fat"`
	Sat_fat        string `json:"sat_fat"`
	Dv_sat_fat     string `json:"dv_sat_fat"`
	Trans_fat      string `json:"trans_fat"`
	Cholest_mg     string `json:"cholest_mg"`
	Dv_cholest     string `json:"dv_cholest"`
	Sodium_mg      string `json:"sodium_mg"`
	Dv_sodium      string `json:"dv_sodium"`
	Total_carb     string `json:"total_carb"`
	Dv_carb        string `json:"dv_carb"`
	Fiber          string `json:"fiber"`
	Dv_fiber       string `json:"dv_fiber"`
	Total_sugar    string `json:"total_sugar"`
	Added_sugar    string `json:"added_sugar"`
	Dv_sugar       string `json:"dv_sugar"`
	Protein        string `json:"protein"`
	Vit_d          string `json:"vit_d"`
	Calcium        string `json:"calcium"`
	Iron           string `json:"iron"`
	Potass         string `json:"potass"`
	Product_line_1 string `json:"product_line_1"`
	Product_line_2 string `json:"product_line_2"`
	Product_line_3 string `json:"product_line_3"`
}
